allow-unwrap-in-tests = true
allow-expect-in-tests = true
doc-valid-idents = ["NSRL", "CIRCL", "MalwareBazaar", "VirusShare", "Malshare", "AlienVaultOtx", "loldrivers", "BYOVD", "SHA-256", "MD5", "SHA1", ".."]
